name: PHP Tests
on: { push: { branches: [ main, master ] }, pull_request: {} }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: { php-version: '8.2', coverage: none }
      - run: composer install --no-interaction --no-progress
      - run: vendor/bin/phpunit --testdox
